### PR TITLE
Polymer2 & es6

### PR DESCRIPTION
**Pull request by DarkSideOfMo0n**
This PR upgrades iron-grid to polymer 2 and es6. 
It uses ResizeObserver for resize detection.
It is already template string based so that the upcomming upgrade to polymer3 will be painless.
iron-grid-container was moved to its own file.
Inline Demo was added for webcomponents.org

### CODE REVIEW

**Comment by DarkSideOfMo0n** [comment]
up!

**Comment by onlinerahul** [comment]
So will this version available, can we now use with polymer 2?

**Comment by DarkSideOfMo0n** [comment]
Yes if you use latest master it is using polymer 2.

**Comment by onlinerahul** [comment]
what if i need to override  the media breakpoints? because as per the iron-grid.html all the breakpoint trigger using [::content .xs{{3}}-important] so if i need to change how could i use @media rule?

**Pull request merged**
