### PR TITLE
Nested grid management bug fix + hidding element bug fix

### PR DESCRIPTION
**Pull request by maxiplay**

### CODE REVIEW

**Comment by maxiplay** [comment]
Sorry but I don't know how to transform code into documentation code. If you know a tool to do this say me

**Comment by JGSolutions** [comment]
+1 Need this fix as my update broke my layout.

@maxiplay Good job on the fix thanks

**Comment by JGSolutions** [comment]
Very disappointing support. I think I will just use another web component to handle grids!

**Comment by maxiplay** [comment]
Use my repository during wait

**Comment by JGSolutions** [comment]
Well i did get your fixes but at the sametime no response from him

**Comment by mwinandy** [comment]
+1

**Pull request merged**
