### PR TITLE
I think  use  self's width is better.

### PR DESCRIPTION
**Pull request by gemron**
i change it  ;then it work better when it in dialog;

### CODE REVIEW

**Comment by maxiplay** [comment]
I valid. Each iron-grid need to manage its own width.

**Comment by gemron** [comment]
why not?

**Comment by maxiplay** [comment]
Yes why not ?

**Comment by ozwaldorf** [comment]
Pull request is behind #24 @maxiplay @gemron

**Comment by gemron** [comment]
oh yes ! but, #24 is not solve my problem. @The5heepDev 
I changed _onResize  method  .
when grid node's dialog container  change it's width , this grid node to adapt to the width of the dialog container .
I hope it's right ,thanks to make sure it.

**Comment by ozwaldorf** [comment]
@gemron If you add your fix to the latest version, I'll merge.

**Comment by gemron** [comment]
@The5heepDev ok .see #25

**Pull request closed without merging**
